#!/usr/bin/env python3
"""Regenerates HolidayData.swift and HolidayData.kt from holidays-de.json.
Run after fetch.py refreshes the source data."""
import json

SOURCE = "holidays-de.json"
raw = open(SOURCE, encoding="utf-8").read()
# Safety check: this must stay embeddable as a Swift/Kotlin triple-quoted string with no escaping.
assert '"""' not in raw and "\\" not in raw and "${" not in raw and "\n" not in raw, "holidays-de.json is no longer safe to embed verbatim; update generate.py"

swift = f'''// GENERATED by calendar/generate.py from holidays-de.json — do not edit by hand.
import Foundation

/// The bundled Ferien/Feiertage data, as the JSON `HolidayCalendar` parses.
enum HolidayData {{
    static let json = """
{raw}
"""
}}
'''
with open("../Lernwerk/Services/Calendar/HolidayData.swift", "w", encoding="utf-8") as f:
    f.write(swift)

kotlin = f'''package de.maxifrz.lernwerk.holidays

// GENERATED by calendar/generate.py from holidays-de.json — do not edit by hand.

/** The bundled Ferien/Feiertage data, as the JSON [HolidayCalendar] parses. */
object HolidayData {{
    const val JSON = """
{raw}
"""
}}
'''
import os
kotlin_dir = "../android/app/src/main/java/de/maxifrz/lernwerk/holidays"
os.makedirs(kotlin_dir, exist_ok=True)
with open(f"{kotlin_dir}/HolidayData.kt", "w", encoding="utf-8") as f:
    f.write(kotlin)

print("wrote HolidayData.swift and HolidayData.kt,", len(raw), "bytes of JSON each")
