#!/usr/bin/env python3
"""Generates the app icon from Pip's pixel grid (the same one PipView draws) for iOS and Android.

Run from the repository root: python3 scripts/make-icons.py
Needs Pillow for the iOS PNGs.
"""
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent

CAT = [
    ".............",
    ".oo.......oo.",
    ".opo.....opo.",
    ".offo...offo.",
    ".offfffffffo.",
    "offfffffffffo",
    "offeefffeeffo",
    "offeefffeeffo",
    "offfffpfffffo",
    "offfffffffffo",
    ".offfffffffo.",
    ".offwwfffwwo.",
    "..ooooooooo..",
]
TAIL = [(12, 10), (13, 10), (14, 9), (14, 8)]

PALETTES = {
    "light": {"bg": "#FAF9F6", "o": "#23231F", "e": "#23231F", "f": "#7FA98C", "p": "#E5A8A2", "w": "#FFFDF6"},
    "dark": {"bg": "#1E2B23", "o": "#0A0A08", "e": "#0A0A08", "f": "#8FBE9C", "p": "#E5A8A2", "w": "#FFFDF6"},
}


def pixels():
    """(x, y, kind) for every filled cell, tail and its outline included, like PipSimulation.draw."""
    cells = {}
    for y, row in enumerate(CAT):
        for x, kind in enumerate(row):
            if kind != ".":
                cells[(x, y)] = kind
    occupied = set(cells) | set(TAIL)
    for tx, ty in TAIL:
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            if (tx + dx, ty + dy) not in occupied:
                cells.setdefault((tx + dx, ty + dy), "o")
    for cell in TAIL:
        cells[cell] = "f"
    return cells


def bounds(cells):
    xs = [x for x, _ in cells]
    ys = [y for _, y in cells]
    return min(xs), min(ys), max(xs) + 1, max(ys) + 1


def ios_icons():
    cells = pixels()
    x0, y0, x1, y1 = bounds(cells)
    size = 1024
    cell = 44
    width = (x1 - x0) * cell
    height = (y1 - y0) * cell
    left = (size - width) // 2 + cell // 2  # the tail makes the cat look off-center otherwise
    top = (size - height) // 2 + cell // 2
    folder = ROOT / "Lernwerk/Resources/Assets.xcassets/AppIcon.appiconset"
    folder.mkdir(parents=True, exist_ok=True)
    for name, palette in PALETTES.items():
        image = Image.new("RGB", (size, size), palette["bg"])
        draw = ImageDraw.Draw(image)
        for (x, y), kind in cells.items():
            px = left + (x - x0) * cell
            py = top + (y - y0) * cell
            draw.rectangle([px, py, px + cell - 1, py + cell - 1], fill=palette[kind])
        image.save(folder / f"AppIcon-{name}.png")
    (folder / "Contents.json").write_text(
        """{
  "images" : [
    {
      "filename" : "AppIcon-light.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "filename" : "AppIcon-dark.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
"""
    )
    (folder.parent / "Contents.json").write_text('{\n  "info" : {\n    "author" : "xcode",\n    "version" : 1\n  }\n}\n')


def vector(cells, kinds_colors, cell, left, top):
    """One <path> per color; every cell becomes a small square subpath."""
    paths = []
    for color, kinds in kinds_colors:
        parts = []
        for (x, y), kind in sorted(cells.items()):
            if kind in kinds:
                px = round(left + x * cell, 2)
                py = round(top + y * cell, 2)
                # Slightly oversized squares so antialiasing does not show seams between cells.
                parts.append(f"M{px},{py}h{cell + 0.05:.2f}v{cell + 0.05:.2f}h-{cell + 0.05:.2f}z")
        if parts:
            paths.append(f'    <path\n        android:fillColor="{color}"\n        android:pathData="{"".join(parts)}" />')
    return "\n".join(paths)


def android_icons():
    cells = pixels()
    x0, y0, x1, y1 = bounds(cells)
    cell = 3.4  # 108 dp canvas, the launcher mask keeps the middle 66 dp
    width = (x1 - x0) * cell
    height = (y1 - y0) * cell
    left = 54 - width / 2 - x0 * cell + cell / 2
    top = 54 - height / 2 - y0 * cell + cell / 2
    light = PALETTES["light"]
    header = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by scripts/make-icons.py: Pip, the pixel cat, on the 108 dp adaptive-icon grid. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n    android:height="108dp"\n'
        '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
    )
    res = ROOT / "android/app/src/main/res"
    foreground = vector(cells, [(light[k], {k}) for k in ("o", "f", "p", "w")] + [(light["e"], {"e"})], cell, left, top)
    (res / "drawable/ic_launcher_foreground.xml").write_text(header + foreground + "\n</vector>\n")
    # Themed icons (Android 13+) tint one shape: the outline and eyes read as a line drawing of the cat.
    monochrome = vector(cells, [("#FF000000", {"o", "e", "p"})], cell, left, top)
    (res / "drawable/ic_launcher_monochrome.xml").write_text(header + monochrome + "\n</vector>\n")
    (res / "values/ic_launcher_colors.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        f'    <color name="ic_launcher_background">{light["bg"]}</color>\n</resources>\n'
    )
    (res / "mipmap-anydpi-v26/ic_launcher.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
        "</adaptive-icon>\n"
    )


if __name__ == "__main__":
    ios_icons()
    android_icons()
    print("Icons written.")
